services:
    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SeguridadBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        # exclude: '../../{Tests,Resources}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    SeguridadBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    seguridad.login_form_authenticator:
        class: SeguridadBundle\Security\LoginFormAuthenticator
        autowire: true


    app.doctrine.hash_password_listener:
        class: SeguridadBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }